---
engines:
  csslint:
    enabled: true
	checks:
      important:
        enabled: false
		#necessary for hidden styles
      box-sizing:
        enabled: false
		#who the hell still uses IE 6
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
