var smileList = [
	"closed-smile",
	"cool",
	"full-grin",
	"halo",
	"grin",
	"hugging-smile",
	"nerd",
	"open-grin",
	"relieved",
	"s-smile",
	"squint-grin",
	"squint-smile",
	"u-down"
];
$('#smile').text(smileList[Math.floor(Math.random()*smileList.length)]);

var emojiList = [
	"rocket",
	"nerd",
	"cheese",
	"horns-d",
	"money-mouth",
	"bell",
	"celebration-d",
	"u-down",
	"antique-key",
	"fire",
	"bee",
	"chipmunk",
	"crab",
	"dolphin",
	"dove",
	"dragon",
	"hatching-chick",
	"lion",
	"monkey",
	"octopus",
	"penguin",
	"poodle",
	"spouting-whale",
	"standing-chick",
	"tiger",
	"turtle",
	"unicorn"
];
$('#set').text(emojiList[Math.floor(Math.random()*emojiList.length)]);